AirBooks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("contact/", include("contact.urls")),
    path("about/", include("about.urls")),
    path("register/", include("register.urls")),
    path("login/", include("login.urls")),
    path("", include("flights.urls")),
]

about/urls.py
from django.urls.conf import path
from .views import about_view

# app_name = "about"

urlpatterns = [
    path("", about_view, name="about"),
]

contact/urls.py
from django.urls.conf import path
from . import views

# app_name = "contact"

urlpatterns = [path("", views.contact_view, name="contact")]

flights/urls.py
from django.urls.conf import path

from flights.views import book_view, flights_details_view, flights_search_view

app_name = "flights"

urlpatterns = [
    path("book", book_view, name="book"),
    path("details", flights_details_view, name="details"),
    path("search", flights_search_view, name="search"),
]

home/urls.py
from django.urls.conf import path
from .views import home_view

# app_name = "home"

urlpatterns = [
    path("", home_view, name="home"),
]

login/urls.py
from django.urls.conf import path
from . import views


urlpatterns = [path("", views.login_view, name="login")]

register/urls.py
from django.urls import path

from .views import register_view

# app_name = "register"

urlpatterns = [
    path("", register_view, name="register"),
]

accounts/models.py
from django.db import models

# Create your models here.

flights/models.py
# from django.db import models
# from django.db.models.enums import Choices
# from django.db.models.fields import DateField, DateTimeField, IntegerField, TimeField
# from django.urls.base import reverse
# from django_countries.fields import CountryField

# # Create your models here.
# ############################################################################################
# class Airline(models.Model):
#     name = models.CharField(max_length=100, db_index=True)
#     number = models.IntegerField(db_index=True)
#     slug = models.SlugField(max_length=100, unique=True)

#     class Meta:
#         verbose_name_plural = "Flights"

#     def __str__(self):
#         return self.name


# ############################################################################################


# class City(models.Model):
#     name = models.CharField(max_length=100, db_index=True)
#     slug = models.SlugField(max_length=100, unique=True)
#     # country = models.ForeignKey(
#     #     Country, related_name="country", null=False, on_delete=models.CASCADE
#     # )

#     class Meta:
#         verbose_name_plural = "Cities"

#     def __str__(self):
#         return self.name


# ############################################################################################


# class Country(models.Model):
#     name = CountryField()
#     slug = models.SlugField(max_length=100, unique=True)
#     city = models.ForeignKey(
#         City, related_name="city", null=False, on_delete=models.CASCADE
#     )

#     class Meta:
#         verbose_name_plural = "Countries"

#     def __str__(self):
#         return self.name


# ############################################################################################


# class Airports(models.Model):
#     name = models.CharField(max_length=100, db_index=True)
#     slug = models.SlugField(max_length=100, unique=True)
#     country = models.ForeignKey(
#         Country, related_name="country", null=False, on_delete=models.CASCADE
#     )
#     city = models.ForeignKey(
#         City, related_name="city", null=False, on_delete=models.CASCADE
#     )

#     class Meta:
#         verbose_name_plural = "Airports"

#     def __str__(self):
#         return self.name


# ############################################################################################
# class Flight(models.Model):
#     name = models.CharField(max_length=100, db_index=True)
#     slug = models.SlugField(max_length=100, unique=True)
#     flight_name = models.ForeignKey(Airline, null=False, on_delete=models.CASCADE)
#     flight_number = models.IntegerField()
#     airport_name = models.ForeignKey(
#         Airports, related_name="airport", null=False, on_delete=models.CASCADE
#     )
#     Depature_date = DateTimeField(auto_now_add=True)
#     Depature_day = DateField(auto_now_add=True)
#     Arrival_day = DateField(auto_now_add=True)
#     Arrival_date = DateTimeField(auto_now_add=True)
#     Depature_time = TimeField(auto_now=True)
#     Arrival_time = TimeField(auto_now=True)
#     Seat_number = IntegerField()
#     # flight_type = Choices()
#     country = models.ForeignKey(
#         Country, related_name="country", null=False, on_delete=models.CASCADE
#     )
#     city = models.ForeignKey(
#         City, related_name="city", null=False, on_delete=models.CASCADE
#     )

#     class Meta:
#         verbose_name_plural = "Flights"

#     def __str__(self):
#         return self.name

register/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class User(models.Model):
    firstname = models.CharField( max_length=150)
    lastname = models.CharField(max_length=150)
    username = models.CharField(max_length=150)
    email = models.EmailField( max_length=150)
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    country = models.CharField(max_length=150)
    gender = models.CharField(max_length=150)
    password = models.CharField(max_length=150)
    confirmpassword = models.CharField(max_length=150)
    created_date = models.DateField()
     
    

about/views.py
from django.shortcuts import render

# Create your views here.
def about_view(request):
    return render(request, "about.html")

accounts/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.
def contact_view(request):
 return render(request,"contact.html")

flights/views.py
from django.shortcuts import render

# Create your views here.


def book_view(request):
    return render(request, "book.html")


###########################################################################
def flights_search_view(request):
    return render(request, "book_flight_search.html")


###########################################################################


def flights_details_view(request):
    return render(request, "flight_details.html")


###########################################################################


def passenger_details_view(request):
    return render(request, "flight_details.html")


###########################################################################


def passenger_form_view(request):
    return render(request, "flight_details.html")


###########################################################################

home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
 return render(request,"home.html")

login/views.py
from django.shortcuts import render

# Create your views here.
def login_view(request):
    return render(request, "login.html")

register/views.py
from django.shortcuts import render
from . import models

#######################################################################

# Create your views here.
def register_view(request):
    return render(request, "register.html")


#######################################################################


#######################################################################

templates/about.html
{% extends 'base.html'%} {% block content %}
<div>
  <br />
  <!-- ======= About Us Section ======= -->
  <div class="container p-2">
    <div class="card box-shadow">
      <div class="card-head">
        <div class="section-title">
          <h2>
            <strong>ABOUT</strong>
          </h2>
          <hr />
          <p class="p p-5">
            Airbooks.com is a private site that provides you with access to
            instant Flight Departures, Arrivals, Time Shedules across different
            countries instantly....
          </p>
        </div>
      </div>
      <div class="card-body">
        <section id="about" class="about">
          <div class="container-form">
            <div class="column">
              <div class="col-12 pt-4 pt-lg-0 order-2 order-lg-1 content">
                <p class="font-italic">
                  For Inquiries, General Information, please send a Email:
                  <strong>Airbooks@gmail.com</strong> and response with be
                  provided Shortly.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <br />
  <br />
  <!-- @*#############################################################################*@ -->
  <!-- End About Us Section -->
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AirBooks</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static '/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static '/site.css' %}" />
      <script src="{% static '/jquery-3.6.0.slim.min.js' %}"></script>
      <script src="{% static '/popper.min.js' %}"></script>
      <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
  </head>

  <body>
    {% include 'navheader.html'%}

    <main role="main" class="pb-3">{% block content%} {% endblock%}</main>
    {% include 'footer.html'%}
  
  </body>
</html>

templates/book.html
{% extends 'base.html'%} {% block content %}
<br />
<div class="container">
  <div class="text-center">
    <div class="text-center">
      <h1 class=""><strong>BOOK FLIGHT</strong></h1>
    </div>

    <hr />
    <div class="row text-center p-3">
      <div class="col-md-6 mx-auto">
        <form asp-action="Login" method="post">
          {% csrf_token %}
          <div asp-validation-summary="ModelOnly" class="text-danger"></div>

          <div class="form-group row mb-3">
            <div class="col-md-12">
              <label>FROM?</label>
              <select name="GenreId" class="form-control">
                <option class="form-control" value="0">
                  From which City...
                </option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-12">
              <label>TO? </label>
              <select name="GenreId" class="form-control">
                <option class="form-control" value="0">
                  Choose a Destination...
                </option>
              </select>
            </div>
          </div>
          <br />
          <hr />
          <div class="col-md-4 mx-auto">
            <button
              type="submit"
              class="btn btn-primary text-white"
              id="login"
              value="Login"
            >
              <strong>SEARCH</strong>
            </button>
          </div>
        </form>
      </div>
    </div>

    <br />
    <br />
  </div>
</div>
{% endblock %}

templates/book_flight_search.html
{% extends 'base.html'%} {% block content %} {% load static %}
<br />
<div class="container card  ">
  <br />
  <div class="card-head bg-dark mx-auto my-auto box-shadow w-25 rounded shadow">
    <div class="row justify-content-center mx-auto col-12 pt-2 box-shadow">
      <h4 class="text-white text-center" >
        <strong>AVAILABLE FLIGHTS</strong>
      </h4>
    </div>
  </div>
  <br />
  <div class="card-body bg-light box-shadow m-4">
    <table class="table table-hover table-striped table-responsive-sm">
      <thead>
        <tr class="text-dark">
          <th class="text-center ">#</th>
          <th class="text-center ">AIRLINE LOGO</th>
          <th class="text-center ">COMPANY NAME</th>
          <th class="text-center ">FLIGHT NAME</th>

          <th class="text-center ">FLIGHT NUMBER</th>
          <th class="text-center ">ACTIONS</th>
        </tr>
      </thead>

      <tbody>
        <tr class="text-dark">
          <td class="text-center  py-5">1</td>
          <td class="text-center py-4">
            <img src="#" class="artwork" height="70" width="70" />
          </td>
          <td class="text-center  py-5"></td>
          <td class="text-center  py-5"></td>
          <td class="text-center  py-5"></td>
          <td class="text-center  py-5">
            <button class="btn btn-primary">BUY TICKET</button>
            <button class="btn btn-info">VIEW DETAILS</button>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <div
            class="text-center my-auto pt-3 text-center"
            style="height: 60px"
          >
            <h3 class="text-dark"><strong>NO FLIGHTS AVAILABLE</strong></h3>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
  <br />
  <br />
{% endblock %}

templates/contact.html
{% extends 'base.html'%} {% block content %}
<!-- ======= Contact Section ======= -->
<br />
<div class="container col-sm-9">
  <div class="card box-shadow">
    <div class="card-head">
      <div class="section-title">
        <h2><strong>CONTACT</strong></h2>
        <p class="">Experiencing a Problem?</p>
      </div>
    </div>
    <hr />

    <div class="card-body">
      <section id="contact" class="contact">
        <div class="container-form">
          <div class="column">
            <!-- ################################################ -->
            <div class="col-lg-7 mt-3 mt-lg-0 d-flex align-items-stretch">
              <form
                action="forms"
                method="post"
                role="form"
                class="php-email-form"
              >
                <input
                  type="hidden"
                  name="id"
                  class="form-control"
                  id="name"
                  asp-for="Id"
                />

                <div class="form-group">
                  <input
                    type="text"
                    name="name"
                    placeholder="Your Name"
                    class="form-control"
                    id="name "
                    style="width: 400px"
                  />
                  <div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                  </div>
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    class="form-control"
                    placeholder="Email "
                    name="email "
                    id="email"
                    style="width: 400px"
                  />
                  <div>
                    <span asp-validation-for="Email" class="text-danger"></span>
                  </div>
                </div>
                <div class="form-group">
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Subject "
                    name="subject "
                    id="subject"
                    style="width: 400px"
                  />
                  <div>
                    <span
                      asp-validation-for="Subject"
                      class="text-danger"
                    ></span>
                  </div>
                </div>
                <div class="form-group">
                  <textarea
                    class="form-control"
                    placeholder="Message "
                    name="message "
                    rows="10 "
                    data-rule="required "
                    data-msg="Please write something for us "
                  ></textarea>
                  <div>
                    <span
                      asp-validation-for="Message"
                      class="text-danger"
                    ></span>
                  </div>
                </div>
                <!-- <div class="mb-3">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">
                    Your message has been sent. Thank you!
                  </div>
                </div> -->
                <br />
                <div class="text-center">
                  <button type="submit" class="btn btn-success" value="">
                    SEND
                  </button>
                </div>
                <br />
              </form>
            </div>
            <!-- ################################################ -->
          </div>
        </div>
      </section>
    </div>
  </div>
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
</div>
<br />

<!-- End Contact Section -->

{% endblock %}

templates/dashboard.html
{% extends 'base.html'%} {% block content %} {% load static %} {% endblock %}
<div class="container">
  <!-- nav -->
  <div class="col-4">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="#">BOOKINGS HISTORY</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CHANGE PASSWORD</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">EDIT ACCOUNT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">DELETE ACCOUNT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">LOGOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>

  <div class="col-8 text-center">DASBOARD</div>
</div>

templates/flight_details.html
{% extends 'base.html'%} {% block content %} {% load static %}
<br />
<div class="text-center container">
  <h2 class="text-info"><strong>FLIGHT DETAILS</strong></h2>
</div>
<hr />

<div class="container">
<div class="row card text-center m-3">
  <div class="bd-example bd-example-images m-4">
    <div class="text-center">
      <img src="#" id="productsDetailsimage" class="artwork" width="300" alt="" />
    </div>
    <div class="text-center">
      <hr class="btn-dark w-50 text-center mx-auto" />
      <h6>FlightName</h6>
      <h6>FlightNunber</h6>
      <h6 class="text-info">
        <strong>name</strong>
      </h6>
      <h6>Country</h6>
      <h6>description</h6>
      <hr class="btn-dark w-50 text-center mx-auto" />
      <h6 class="text-info">
        <strong>$price</strong>
      </h6>
      <a class="btn button btn-dark  m-0"><strong>PURCHASE TICKET</strong></a>
    </div>
  </div>
</div>
<hr />
</div>

{% endblock %}

templates/footer.html
{% block content %}

<footer class="border-top footer bg-default">
  <div class="container text-center text-black">&copy; AIRBOOKS</div>
</footer>
{% endblock %}

templates/home.html
 {% extends 'base.html'%} {% block content %}
{% load static %}
<div id="carouselExampleControls" class="carousel slide col-sm-12 m-0 p-0 w-100 bg-danger" data-ride="carousel">
    <div class="carousel-inner m-0 p-0 w-100">
        <div class="carousel-item active carousel">
            <img class="overflow-hidden img-thumbnail border-0 w-100  m-0 p-0" src="{% static '/images/ual_b787-8_livery_170719_wpc_a1-003.jpg'%}">
            <div class="carousel-caption d-md-block">
                <h2 class=" m-0 mt-md-1 mt-sm-0 " id="header"><strong>SWIFT FLIGHT BOOKINGS</strong></h2>
                <!-- <p class="text-dark"><strong>Get access to instant Flight Departures, Arrivals, Time Shedules across different countries instantly...</strong></p> -->
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br>
<!-- @*#######################################################################*@ -->

<hr class="m-0 p-0" />
<!-- @*#######################################################################*@ -->

<div class="container">
        <div class="col-sm-12 mx-auto text-center">
            <br>
            <h4 class="font-weight-bold  " id="textshadow2"><strong>TOP DESTINATIONS</strong></h4>
            <br>
        </div>
    <div class="mx-auto ">
        <div class="mx-auto justify-content-center countrydisplay">
         <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/900_12322018HighRes.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>CHICAGO</h6>
            </div>
        </div>   
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/canada-country.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>CANADA</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/UK.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>UNITED KINGDOM</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/china-in-pictures-beautiful-places-to-photograph-south-putuo-temple.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>CHINA</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/AdobeStock_104060928.jpeg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>AUSTRALIA</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/New-Zealand-Reaches-100-Day-Milestone-Without-Coronavirus-Transmission.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>NEW ZEALAND</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/Night_Look_of_Nanpu_Bridge_and_Spiral_Road_in_Country_China.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>JAPAN</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/brazil.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>BRAZIL</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images m-1">
            <div class="text-center">
                <img src="{% static '/images/newyork-scenic-night-2000-1075x840.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>NEW YORK</h6>
            </div>
        </div>
        <div class="bd-example bd-example-images  m-1">
            <div class="text-center">
                <img src="{% static '/images/ss-bosphorus-bridge-121566550__1920x1080.jpg' %}" class="artwork" height="100" width="100">
                <hr class="btn-dark">
                <h6>PARIS</h6>
            </div>
        </div>
        </div>
        </div>

      <!-- #################### -->
    </div>
</div>

<!-- @*#############################################################################*@ -->
<div>
    <hr class="my-4 " />
</div>
<br/>

<!-- @*#############################################################################*@ -->
<div class=" container">
<div class=" d-flex  justify-content-center bg-light">
    <div class="card col-6 text-center p-5 border-0">
        <strong>What does AirBook do?</strong>
        <br/>
        <br/>
        <div class="text-muted">
            Airbooks is your one stop travel online shop. Quick access to access latest flight prices and available 
            flights, ticket prices for both international and domestic from your favourite airlines...
        </div>
    </div>
    <div class="col-6 text-center p-5">
       <strong> Why book with Airbooks?</strong>
        <br/>
        <br/>

       <div class="text-muted">Spending long hours on queues is a thing of the past, hunting and changing plans accomodating
           your present or future time schedule gets easier with Airbooks..Also compare fights prices helps you to determine
           the best flights that mights suit you before buying a ticket....
       </div>
    </div>
</div>
</div>
<br/>
<br/>
<!-- @*#######################################################################*@ -->

<div class="container">
<div class=" text-center bg-dark text-white p-4 m-2 mx-auto" >
    <ul class="list-unstyled">
        <li class="">Airbooks does the searching you do the rest...</li>
        <li class="">Search hundreds of travel suites at ago ...</li>
        <li>Know when to book with price filters...</li>
        <li>Find the right information you need to make the right decision...</li>
    </ul>
</div>
</div>


<br />
<br />
<!-- @*#############################################################################*@ -->
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <h4 class="font-weight-bold" id="textshadow2"><strong>CONNECT</strong></h4>
            <br />
        </div>
        <div class="col-12">
        <div class=" ">
            <div class=" d-flex col-12 justify-content-center bg-light">
                <div class="col-6 text-center p-5">
                    <strong>Customer Support</strong>
                    <br />
                    <br />
                    <div class=" card border-0 text-muted">
                        <div class="p-4">
                            Get in touch for changes, cancellations & assistance
                            <br/><br />
                            <div>
                                <button class="btn btn-dark">Contact Us</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<br />
<br />

<br />
<br /><br />
<br />
<!-- @*#######################################################################*@ -->

{% endblock %}

templates/navheader.html
{% load static %}
<link rel="stylesheet" href="{% static '/site.css' %}" />
<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" />
<script src="{% static '/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static '/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>

<nav class="container navbar navbar-expand-lg navbar-light bg-white mx-auto">
  <a class="navbar-brand text-black py-2" href="{% url 'home'%}"
    ><strong>AIRBOOKS</strong></a
  >
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item py-2">
        <a class="nav-link active text-black" href="{% url 'flights:book' %}">BOOK FLIGHT</a>
      </li>
      <li class="nav-item py-2">
        <a class="nav-link text-black" href="/admin/">ADMIN</a>
      </li>
      <li class="nav-item py-2">
        <a class="nav-link text-black" href="{% url 'register'%}">REGISTER</a>
      </li>
      <li class="nav-item py-2">
        <a class="nav-link text-black" href="{% url 'login' %}">LOGIN</a>
      </li>
      <li class="nav-item py-2">
        <a class="nav-link text-black" href="{% url 'contact'%}">CONTACT</a>
      </li>
      <li class="nav-item py-2">
        <a class="nav-link text-black" href="{% url 'about'%}">ABOUT</a>
      </li>
      <!-- <li class="nav-item dropdown show py-2">
        <a
          class="nav-link dropdown-toggle text-black"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          FLIGHTS RESERVATION
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item text-black" href="/flights/">BOOK FLIGHT</a>
          <a class="dropdown-item text-black" href="#">COUNTRIES</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-black" href="#">LOGOUT</a>
        </div>
      </li> -->
    </ul>
    <form class="d-flex form-inline my-2 py-2 my-lg-0">
      <input
        class="form-control mr-sm-1 mx-1"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      <a class="btn btn-success my-2 my-sm-0" type="submit" href="{% url 'flights:search'%}">Search</a>
    </form>
  </div>
</nav>
<hr class="m-0" />